import "dotenv/config";
import express from "express";
import cors from "cors";
import http from "http";
import { Server } from "socket.io";
import mongoose from "mongoose";
import authRoutes from "./routes/authRoutes.js";
import projectRoutes from "./routes/projectRoutes.js";
import taskRoutes from "./routes/taskRoutes.js";
import commentRoutes from "./routes/commentRoutes.js";
import notificationRoutes from "./routes/notificationRoutes.js";

const app = express();
const server = http.createServer(app);
const io = new Server(server, { cors: { origin: process.env.CLIENT_URL || "http://localhost:5173", credentials: true } });
app.use(cors({ origin: process.env.CLIENT_URL || "http://localhost:5173", credentials: true }));
app.use(express.json());
app.get("/api/health", (_req,res)=>res.json({ok:true, service:"project-3-api"}));
app.use("/api/auth", authRoutes);
app.use("/api/projects", projectRoutes);
app.use("/api/tasks", taskRoutes);
app.use("/api/comments", commentRoutes);
app.use("/api/notifications", notificationRoutes);
io.on("connection", socket => { socket.on("joinProject", projectId => socket.join(`project:${projectId}`)); });
app.set("io", io);
const port = process.env.PORT || 5000;
mongoose.connect(process.env.MONGO_URI).then(() => server.listen(port, () => console.log(`API running on http://localhost:${port}`))).catch(err => { console.error("MongoDB connection failed:", err.message); process.exit(1); });